blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/NfH6mGFuAB
    about: Please use the Plex Meta Manager Discord to ask for support.
  - name: Discussions
    url: https://github.com/meisnate12/pmmutil/discussions
    about: Please use Discussions to ask for support.